server:
  port: 2333
lavalink:
  server:
    password: "Lawda@2969"
    sources:
      youtube: false
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.1"
      repository: "https://maven.lavalink.dev/releases"
plugins:
  youtube:
    enabled: true
    allowSearch: true
    clients:
      - MUSIC
      - TV
      - ANDROID_VR
      - WEB
      - WEBEMBEDDED
    oauth:
      enabled: true
