services:
  - type: web
    name: lavalink
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: LAVALINK_SERVER_PASSWORD
        sync: false
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx512m
